<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <InvariantGlobalization>false</InvariantGlobalization>
    <Product>RideAudit</Product>
    <Company>RideAudit contributors</Company>
    <Copyright>Copyright (C) 2026 RideAudit contributors</Copyright>
    <Version>0.2.0</Version>
    <Authors>Sharp Ninja</Authors>
    <PackageLicenseExpression>GPL-2.0-only</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
