<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Google.Protobuf" Version="3.36.1" />
    <PackageVersion Include="Grpc.AspNetCore" Version="2.84.0" />
    <PackageVersion Include="Grpc.Core.Api" Version="2.84.0" />
    <PackageVersion Include="Grpc.Net.Client" Version="2.84.0" />
    <PackageVersion Include="Grpc.Tools" Version="2.84.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="Avalonia" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Android" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Headless" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Headless.XUnit" Version="12.1.3" />
    <PackageVersion Include="Xamarin.AndroidX.Core.SplashScreen" Version="1.0.1.15" />
    <PackageVersion Include="SharpNinja.Avalonia.RemoteControl.Runtime" Version="0.8.0" />
    <PackageVersion Include="SharpNinja.Avalonia.RemoteControl.Protocol" Version="0.8.0" />
    <PackageVersion Include="SharpNinja.aiUnit" Version="3.0.0" />
    <PackageVersion Include="Svg.Skia" Version="5.2.3" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
  </ItemGroup>
</Project>
