<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>RideAudit.Ingest</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RideAudit.Contracts\RideAudit.Contracts.csproj" />
    <ProjectReference Include="..\RideAudit.Sec\RideAudit.Sec.csproj" />
  </ItemGroup>
</Project>
